CREATE DATABASE IF NOT EXISTS users_database;

use users_database;


CREATE TABLE IF NOT EXISTS USER 
(
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
EMAIL VARCHAR(20),
PASSWORD VARCHAR(256), 
PRIMARY KEY (ID),
UNIQUE KEY (EMAIL)
);


SELECT * FROM USER;

DROP TABLE IF EXISTS USER;

DROP DATABASE IF EXISTS users_database;